;;;CONTADOR BINARIO SIN RETARDO;;;
;;;RUTINAS DE RETARDO;;;;;;;;;;;;;
;;;CALCULO DE TIEMPOS DE EJECUCUIÓN;;;;

	.INCLUDE "M8535DEF.INC"		;LIBRERÍA PARA EL MODELO DEL MICRO
	.CSEG		
	.ORG	$0					;DIRECCIÓN DE INICIO DE MEMORIA
	RJMP	INICIO				;SALTA A LA ETIQUETA INICIO
	.ORG	$015
					
 INICIO:
	LDI		R16,	LOW(RAMEND)	;PONE EN BAJO LA ULTIMA DIRECCIÓN DE LA MEMORIA RAM
	OUT		SPL,	R16			
	LDI		R16,	HIGH(RAMEND);PONE EN ALTO LA ÚLTIMA DIRECCIÓN DE LA MEMORIA RAM
	OUT		SPL,	R16		 
	LDI		R16,	$FF			;SE LE ASIGNA EL VALOR $FF A R16 = 1111 1111 ESTO QUIERE DECIR QUE SE DEFINIRA TODO EL PUERTO B(8 BITS) COMO SALIDA
	
	OUT		DDRB,	R16			;MANDA EL VALOR DE R16 A DDRB AQUÍ SE DEFINEN SI LOS PUERTOS SERÁN ESTRADAS = 0 O SALIDAS = 1

LOOP:
	OUT		PORTB,	R16			;MANDA EL VALOR DE R16 AL PUERTO B
	INC		R16
	RJMP	LOOP
