;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;PROGRAMA PARA LA TRANSMICIÓN DE UNA CADENA;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	.include "m8535def.inc"
	.cseg		;QUE TODO LO QUE SIGUE VA A LA MEMORIA DE CÓDIGO
	.org $0		;DESDE DIRECCIÓN CERO EMPIEZA
	rjmp INICIO

TABLA:	.DB	"IPN-ESCOM.MICROCONTROLADORES.PAZITO.2014$" ;DIRECTIVA DE TABLA PARA MANDAR DATOS SON FIJOS
;TODO LO QUE ESTÉ ENTRE COMILLAS SE ENVÍA NÚMERO DE CARACTERES DEBE DE SER PAR


INICIO: 
	LDI 	R16, 	LOW(RAMEND)		;;;
	OUT 	SPL, 	R16				;;;SE INICIALIZA EL START POINT
	LDI 	R16, 	HIGH(RAMEND)	;;;
	OUT 	SPH, 	R16				;;;

	LDI 	R17, 	$24				;;;SE CARGA VALOR 24 QUE ES EL ASCII DE '$'

	LDI		R16,	77				;;;SE CONFIGURA LA FRECUENCIA 9600@12MHz	
	OUT 	UBRRL, 	R16				;;;

	SBI		UCSRB,	TXEN			;;;SE ENCIENDE EN MODO DE TRANSMICIÓN
				
	LDI		ZL,		LOW(TABLA<<1)	;;LA CARGA EN DOS PARTES EN PARTE ALTA Y BAJA LA DIRECCIÓN
	LDI		ZH,		HIGH(TABLA<<1)	;;DE LA TABLA DEL PRIMER ELEMENTO VA UNO A LA VEZ

	LPM								;CARGA REEGISTRO R0 CON VALOR DE Z QUE EN ESTE CASO ES EL
									;CÓDIGO ASCII DEL PRIMR CARACTER PARTE ALTA Y BAJA							

ENVIA:
	OUT		UDR,	R0				;;;SE TRANSMITE CARACTER

LOOP:
	SBIS	UCSRA,	UDRE			;;SE ESPERA EL FIN DE TRANSMICIÓN DEL CARACTER
	RJMP	LOOP			
	ADIW	ZL,		1				;;ASIGNA A 'Z' Z+1 SE INSREMENTA Z APUNTA AL SIG. ELEMENTO
	LPM								;;;CARGA R0 CON EL NUEVO VALOR DE 'Z'
	CPSE	R0,		R17				;;COMPARA Y ESCAPA SI ES IGUAL ES IGUAL A UN IF
									;;LO ESTA COMPARANDO CO R17=$24=$
	RJMP	ENVIA					;;SI ES FALSO: LO TANTO LO ENVIA

	LDI		R22,	$40				;;SI ES VERDADERO: SE SALTA LA SIG LÍNEA Y PASA A ESTA 
									;;LINEA DIRECTAMENTE			
	

DELAY:
	DEC 	R20
	BRNE 	DELAY
	DEC 	R21
	BRNE 	DELAY
	DEC		R22
	BRNE	DELAY
	RJMP	INICIO
