;
; prac0Ass.asm
;
; Created: 04/04/2016 04:03:53 p.m.
; Author : Ricardo Ruiz Maldonado
;

			.INCLUDE "M8535DEF.INC"
			.CSEG
			.ORG $0
			RJMP INICIO
			.ORG $015
INICIO:		LDI R16, $FF	;CARGO R16 CON $FF
			OUT DDRB, R16	;CONFIGURO PUERTO B COMO SALIDA
LOOP:		OUT PORTB, R16	;ESCRIBO DATO EN PUERTO B
			INC R16		;INCREMENTO DATO
			RJMP LOOP	;SALTO A LOOP