
	.include "m8535def.inc"
	.cseg		;QUE TODO LO QUE SIGUE VA A LA MEMORIA DE CÓDIGO
	.org $0		;DESDE DIRECCIÓN CERO EMPIEZA
	rjmp INICIO



INICIO: 
	LDI 	R16, 	LOW(RAMEND)		;;;
	OUT 	SPL, 	R16				;;;SE INICIALIZA EL START POINT
	LDI 	R16, 	HIGH(RAMEND)	;;;
	OUT 	SPH, 	R16				;;;



	LDI		R16,	77				;;;SE CONFIGURA LA FRECUENCIA 9600@12MHz	
	OUT 	UBRRL, 	R16				;;;
	SBI		UCSRB,	RXEN			;;;SE ENCIENDE EN MODO DE RECEPCIÓN
	LDI		R16,	$FF

	OUT		DDRB,	R16		;CONFIGURA PUERTO B Y D COMO SALIDA
	OUT		DDRD,	R16		;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	LDI		R16,	$62		;SE HABILITA MODO PWM EN TIMER2
	OUT		TCCR2,	R16		;;;;;;;;;;;;;;;;

DATO:
	SBIS	UCSRA,	RXC				;;;SE ESPERA DATO RECIBIDO
	RJMP	DATO
	IN		R16,	UDR				;;;LEE DATO RECIBIDO
	OUT		PORTB,	R16				;;;ESCIRBE DATO EN PUERTO B
	OUT		OCR2,	R16
	RJMP	DATO



