; Author : Ricardo Ruiz Maldonado
; Practica 3: Contador binario con retardos (C/Timer1)

			.INCLUDE "M8535DEF.INC"		;LIBRERIA PARA EL MODELO DEL MICRO
			.CSEG		
			.ORG	$0					;DIRECCIÓN DE INICIO DE MEMORIA
			RJMP	INICIO				;SALTA A LA ETIQUETA INICIO
			.ORG	$015				

INICIO:		LDI		R16,	LOW(RAMEND)	;------------------------
			OUT		SPL,	R16			;    INICIALIZAMOS EL 
			LDI		R16,	HIGH(RAMEND);	 STACK POINTER
			OUT		SPL,	R16		 	;------------------------
			LDI		R16,	$FF			;SE LE ASIGNA EL VALOR $FF A R16 = 1111 1111
										;	ESTO QUIERE DECIR QUE SE DEFINIRA TODO EL 
										;	PUERTO B(8 BITS) COMO SALIDA
			;SER	R16     			;SE PUEDE PONER EN LUGAR DE "LDI  R16 $FF" 
										;	YA QUE AUTOMÁTICAMENTE LE PASA EL VALOR DE $FF 
										;	AL REGISTRO SOLO QUE ESE VALOR NO SE PUEDE CAMBIAR
			OUT		DDRB,	R16			;MANDA EL VALOR DE R16 A DDRB AQUÍ SE DEFINEN SI LOS 
										;	PUERTOS SERÁN ESTRADAS = 0 O SALIDAS = 1
			LDI		R16,	$00			;SE LE DA VALOR DE INICIO PARA LA SALIDA AL PUERTO B
										;	QUE SERÁ $00 = 0000 0000
			OUT     PORTB, R16
			LDI		R16,	$02			;SE CONFIGURA TIMER CERO CON VALOR DE 5 = 1024 (FRECUENCIA)
			OUT		TCCR1B,	R16

LOOP:
			IN		R16,	TIFR			;SE LEE TIFR COMPLETO Y SE PASA A UN REGISTRO DE PROPOSITO GENERAL R16
			SBRS	R16,	2				;SE CHECA SI EL BIT 0 ESTÁ EN 1	;
			RJMP	LOOP					;FALSO
			INC		R17						;VERDADERO
			OUT		PORTB,	R17				;SE ESCRIBE CONTEO EN PUERTO B
			LDI		R16,	$04				;SE TIENE QUE APAGAR TIFR PARA QUE SE PONGA EN CERO SE BORRA CON 1 = $01
			OUT		TIFR,	R16				;SE BORRA TIFR	
			RJMP	LOOP
